name: Test Release

on:
  push:
    branches:
      - ci-tests
    tags:
      - 'v*'

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:

            - name: Set up Go 1.22
              uses: actions/setup-go@v4
              with:
                  go-version: 1.22
              id: go

            - name: Check out code into the Go module directory
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Clean up go.mod and go.sum
              run: |
                  go get -v -t -d ./...
                  go mod tidy

            - name: Reset repository to a clean state
              run: git reset --hard HEAD

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v5
              with:
                  version: latest
                  args: release --clean
                  #                  key: ${{ secrets.YOUR_PRIVATE_KEY }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}